language: r
cache: packages
os: linux
dist: xenial

r:
  - 3.5
  - 3.6
  - release
  - devel

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

addons:
  apt:
    packages:
      - libudunits2-dev
      - libprotobuf-dev
      - libv8-dev
      - libjq-dev
      - protobuf-compiler
      - libgdal-dev

r_packages:
  - covr
  - lintr
  - roxygen2
  - pkgdown

after_success:
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - Rscript -e 'roxygen2::roxygenise()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  cleanup: false                          # Don't remove files
  token: $GH_TOKEN                        # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING == "release"

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always 
